# Generated by Django 3.0.3 on 2020-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='part',
            field=models.IntegerField(blank=True, null=True, verbose_name='종류'),
        ),
    ]
