# Generated by Django 3.0.3 on 2020-11-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='audio1_url1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='audio2_url2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='audio3_url3',
        ),
        migrations.RemoveField(
            model_name='report',
            name='video_url1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='video_url2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='video_url3',
        ),
    ]
