# Generated by Django 3.0.3 on 2020-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='share',
            field=models.BooleanField(default=False, verbose_name='공유'),
        ),
    ]
